### ISSUE TITLE
Remove Java2D dependency from domain objects.

### ISSUE THREAD

**Issue by Ooouch1** [oripa/oripa#114]
In domain-driven development, domain objects should not depend on view layer.
Java2D objects (Graphics2D, Line2D, and so on) are in view layer and the domain is messed up now.
The solution is to define interfaces for drawing objects in domain layer, and implement them in view layer.

**Comment by lifesbest23** [comment]
I am not very familiar with domain driven development, but started looking into the code regarding the Java2D objects and found them in many widely implemented interfaces in `oripa.domain.paint`.
I am now wondering if it wouldn't be easiest to just move the entire `oripa.domain.paint*` package to the view layer or if that would go against DDD? Is domain usage in the view layer ok?

This looks like a lot of refactoring if just the drawing part has to be reimplementd in the view layer.

In your last commit #113 you already removed some of the Java2D objects but I found, limited to using 'java.awt.geom.Point2D':

- `oripa.domain.paint.PaintContextInterface` and its implementations for storing the current mouse Position
- `oripa.domain.paint.core.ActionState` and its implementations for transmitting the current mouse Position
- `oripa.domain.paint.geometry.NearestItemFinder` and `NearestVertexFinder` converting the mouse Position into domain compliant Vector2D values

For these cases Point2D could be replaced with Vector2D or similar, but since many actions use the Point in different ways, moving the conversion Classes to View wont help. I am not sure how to handle these classes.

For `Graphics2D` usage I found

- `oripa.domain.paint.GraphicMouseActionInterface` and its implementations
- `oripa.domain.paint.CreasePatternGraphicsDrawer` for painting all lines and vertices of the creasepattern
- `oripa.domain.paint.util.ElementSelector` and `GraphicItemConverter` containing the drawing style/format

These could have their draw functionality removed and implemented from interfaces in the view layer later.

Btw I follow your recent commits and it helps to learn where you want to go with this project.

**Comment by Ooouch1** [comment]
I like the philosophy of domain driven development but unfortunately I don't have experience on it.
So development of ORIPA is an experiment for me.
My understanding of the core of DDD is "keep the domain layer clean and understandable so that it can be used for any environment (web, desktop,...)."
I'm curious about the possibility of hexagonal architecture as well.

In my local commits, I have written a wrapper-like interface of `Graphics2D` which can draw some shapes expressed with `Vector2d` and `OriLine.` I placed the implementation of the interface in "oripa.drawer.java2d" package tentatively.
I noticed that `PictureExporter` depends on Java2D and such a dependency from persistence layer to view layer is strange for me.

>  move the entire oripa.domain.paint* package to the view layer

I agree that this package does some view-and-controller-like jobs. It's difficult for me to decide the place to put such jobs...

> Point2D could be replaced with Vector2D

I've done in local commits. Today I had enough time to do it :)

I'm planning to remove `AffineTransform` dependency from `GraphicMouseActionInterface` because the implementations of this interface don't use it.

Thank you for comments!

**Comment by lifesbest23** [comment]
Ok, I am going to look a little bit deeper in the next few days. For now DDD seems like a more broad approach to MVC...
But since I am new to the entire Software Architect Idea, there might be a lot I am overlooking (or not grasping)

To me there are a few questions that come to mind about clearly defining the domain. 

1. Does the domain include only the crease pattern and provides interfaces to manipulate it?
2. Or does it also include temporary Selection/tool states/input device position/undo history?
3. Or even more information like draw settings (like line color/size/visibility/grid)

The current implementation comes closest to 2. , but I could find arguments to support any of them, as they all might be reusable if implemented correctly.

> wrapper-like interface of Graphics2D
I though you wanted to add Interfaces inside the domain, that can be implementd outside and then applied/added to classes that need them, that would be easier, to implement, but adds unnecessary complexity.
Would you mind pushing that into a branch/fork?

> I noticed that PictureExporter depends on Java2D and such a dependency from persistence layer to view layer is strange for me.

The usage of Java2D in `PictureExporter` could be avoided by reusing your Graphics2D wrapper.

> It's difficult for me to decide the place to put such jobs...
For me too, even in smaller projects it is always hard, when a compromise between abstract ideals and realistic boundries has to be weight out, especially when it is not only seen by two eyes...

The seperation of the  `oripa.domain.paint*` packages from the view layer could also be split in only two parts.
1. the domain containing all logic operations without depending on Graphics2D
2. the `oripa.view.creasepattern` package could be used for the rest.
This leaves the Problem of `PictureExporter` though, thereby your approach creating a new package (could that also be called a layer like view?) `oripa.drawer.java2d` seems best to me.

I am wondering though if the hard seperation between domain and view layer should then also be applied to the new package...

**Comment by Ooouch1** [comment]
> Would you mind pushing that into a branch/fork?

I pushed my commits into oripa/remove_java2d_from_domain branch.

> To me there are a few questions that come to mind about clearly defining the domain.
> 
> 1. Does the domain include only the crease pattern and provides interfaces to manipulate it?
> 2. Or does it also include temporary Selection/tool states/input device position/undo history?
> 3. Or even more information like draw settings (like line color/size/visibility/grid)

Good question. I think `ActionState` describes the progress of business, so I like to put it and its implementations in domain layer.
The choice 1 might lead to an anti-pattern called [anemic domain model](https://martinfowler.com/bliki/AnemicDomainModel.html).
Draw settings should be in view layer, I think.

Extracting objects related to `Graphics2D` (now this is replaced with `ObjectGraphicDrawer`) to view (or controller?) layer is a good choice.
