### ISSUE TITLE
illegal folds check

### ISSUE THREAD

**Issue by MichaelY310** [oripa/oripa#169]
Thank you for making this helpful program!

While using the oripa, it sometimes takes me a long time to find out where the illgal fold is if the cp is too complex. Can you add a feature that can help users find out the position of illegal folds that causes fold failures?

**Comment by Ooouch1** [comment]
Have you tried "Check window" button? It shows you whether some conditions are satisfied or not. If you bring the mouse pointer on red rectangle vertex, you can see the name of violated condition(s).

In general, suggestion of fold correction is difficult because there are many (or infinite) patterns for the fix. If the fold ends without error message but doesn't show the colored folded model window, there might be penetration or drawing accuracy problem. Penetration could be detected but I don't have idea how to show the illegal part of the crease pattern.

Thank you for your suggestion. I will consider more deeply.
