### ISSUE TITLE
Adding a "Flatten" tool 

### ISSUE THREAD

**Issue by JinoBetti** [oripa/oripa#203]
One thing I often need to do with Oripa and I usually find complex, is adding the last missing line for the model to be flat.
I'd like to add a new tool, which would add the last missing line for the foldability check to pass. This will obviously be possible only if certain conditions are fulfilled (eg : maekawa theorem will hold when adding the new line...).

For what I've seen so far, the foldability Rules are based on OriVertex whereas the picker is based on Vertex2d.

With your knowledge of the app, is this new functionality useful, and possible to implement more or less easily?

**Comment by Ooouch1** [comment]
Interesting.

I thought a while and got an idea to obtain the candidate lines for satisfying the Kawasaki theorem. If the Kawasaki theorem is satisfied, then the vertex is foldable in many cases. The algorithm has the taste of science but I think it is not difficult. Once you obtain such candidate lines, you can filter them by other theorems for more precise result. If you can implement an algorithm to test flat foldability on vertex, you will get the exactly required line.

Maybe using `OriVertex` makes the implementation easier because we already have tools to obtain angles between adjacent creases. However, design of user interface would be considerable. If you would like to manipulate the CP on foldability check frame, we have to synchronize the result of the manipulation with the main frame, which might make the code messy.

**Comment by Ooouch1** [comment]
My algorithm for the Kawasaki theorem:

[flatten_by_kawasaki_theorem.pdf](https://github.com/oripa/oripa/files/9242593/flatten_by_kawasaki_theorem.pdf)

**Comment by Ooouch1** [comment]
Done in #215

**Comment by JinoBetti** [comment]
Well done, I just tried the new tool for the first time, and it seems great! (sorry, I have absolutely no time to help right now)
I'll test it more thoroughly next time i use oripa to draw a real CP!
Thank you for your great work and implication!
