### ISSUE TITLE
Default behaviour

### ISSUE THREAD

**Issue by origamifaust** [oripa/oripa#250]
Coming from orihime or other software it feels weird to use oripa now cause of this:
Moving square with right click hold and moving square with single right click.

Is it possible to implement things like moving square with middle wheel of mouse
and deleting lines with single click as well as dragging it will allow us to delete mass area?

Another thing is weird shortcut keys like P is not assigned for perpendicular tool and l is not assigned 
but line tool but angle tool haha

**Comment by Ooouch1** [comment]
I guess you are familiar to orihime and its variations, and I don't think there is a standard way of mouse input for origami software. Actually I use a touch pad instead of a mouse, which disables me to use wheel clicks. So basically your suggestion is not attractive to me.

Rectangle area selection by 2 clicks can be implemented technically but needs another input mode for each existing input mode using such selection. I don't like UI with many modes. Simple is better.

Shortcut key assignment by taking the first character conflicts in some cases, for example, perpendicular bisector v.s. perpendicular segment. 'l' is for length (m for measurement might be better but it conflicts with mirror).

**Comment by origamifaust** [comment]
I also heavily use trackpad instead of mouse when i draw cps lately. But with same shortcuts on both software could allow other users to smoothly transition that's all i was thinking.

**Comment by Ooouch1** [comment]
Standardization of shortcuts sounds good but input method is not always same among software. Some functionalities in Orihime don't exist in ORIPA and vice versa. Furthermore, there is a possibility that ORIPA changes some input method after assigning a shortcut and then the method can differ from other software.
So I think different shortcuts are acceptable.
