### ISSUE TITLE
Background Overlay

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#44]
I don't know if this could be useful to anybody besides me but I would love to have the ability to put an image of a CP I have in the background.
On my journey learning to read and understand crease patterns I started reproducing some of them in Oripa and as the basic measurements are not always apparent to me I would like to have the ability to see the CP I am trying to replicate in the background.

I started a trial implementation locally but I find it hard to understand the basic coding structure of this project. 
The background image and settings (like offset, zoom, tilt) should be stored in a class `oripa.domain.bgimage` which will be stored in `oripa.domain.paint.PaintContext`, as this class is used by` view.main.PainterScreen` (if I wanted to save the background image with the CP I should add stuff to `oripa.doc.Doc`?)

The drawing takes place in `view.main.PainterScreen.paintComponent` where a new `oripa.domain.paint.BGImageDrawer`should be used.

For adding mouse Interactions with the background image an implementation of `oripa.domain.paint.GraphicMouseActionInterface` should be used, and added somehow with a new button in `oripa.view.main.UIPanel` somehow. I don't really get how the mouse actions are changed with buttons in the UIPanel. How could I do that?

I would appreciate any help, and I would be quite interested in helping out where I can in this project. If someone has other suggestions for what a newcomer could contribute I would be happy to help in any way I can like unifying the language resource usage.

**Comment by Ooouch1** [comment]
What kind of image do you want to draw in the background?  .png or .jpg?
Does "interactions with the background image" mean to zoom/move/rotate the BG image or something like that?
If you want to draw png or jpg in background, drawing is easy: draw the picture after clearing the screen. Interaction seems not so difficult. I'm not sure if interaction is done in the way you think or not.

The possibility and difficulty of saving BG image with the CP depends on the format you want to use.
I think CP + BG image as a jpg or png is easy to save.
opx is a XML serialization, so BG image might not be able to be contained.
ORIPA implements convenient tools for saving/loading `Doc` using GUI, so it's not necessary but I recommend to put things to be saved in `Doc`.

Adding a command button is complicated to fit the very stateful UI.
If you want to add a button which is categorized by "input" radio button, you have to implement a `GraphicMouseActionInterface` whose `getEditMode()` returns `INPUT`.
A useful base class `GraphicMouseAction` is in `oripa.domain.paint.core`.
Add a string ID into `oripa.resource.StringID`, and add  a boilerplate case statement creating the implemented action into a large switch-case in `oripa.bind.state.PaintBoundStateFactory.createLineInputState(...)`.
In `UIPanel.constructButtons(...)`, add `lineInputXXXButton = (JRadioButton) buttonFactory.create(...);`
In `UIPanel.addPaintActionButtons(...)`, add `addPaintActionButton(lineInputXXXButton, gridWidth, gridy_start, paintActionButtonCount++);`
Finally, prepare the icon image and add a statement into `UIPanel.setButtonIcons()`.
This instruction might be incomplete because I'm writing while chasing the code.

**Comment by lifesbest23** [comment]
Thanks a lot for your answer it helped me understand the UI interactions better, and I finally got something to work. Changed quite a lot in the UIPanel as well though and since I tried adding a third State besides Input and Select, some things are not working quite as I want yet. I have some cleanup to do.

**Comment by Ooouch1** [comment]
> I finally got something to work.
Congrats.

**Comment by Ooouch1** [comment]
duplication of #173
