### ISSUE TITLE
canceling angle step bug

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#78]
After Cancelling the Angle Step Draw Line  Tool with the escape key, if I click anywhere even a Vertex an IllegalStateException is thrown: `wrong state: impossible vertex selection.`
But still the center Point is getting selected.
With any other way of canceling line input (at least to my knowledge) this error does not occur.

**Comment by Ooouch1** [comment]
Escape is originally intended to unselect all lines in line-selection mode. This bug is caused by my changes which don't care what mode is now and clear all selections.
Resetting the selections by the escape key seems convenient, so I'll fix the bug so that the escape key invokes such an action.
Drawing tools use state pattern so I need to initialize it on the invocation as well 😄

Thanks for reporting.

**Comment by lifesbest23** [comment]
Good to know that Escape is not generally used for a foll tool reset but only for deselecting (of lines and vertices?).
Since I am not really into CP designing it is hard for me to test functions on complex models but I try out some actions that seem reasonable to me every once in a while.
