### ISSUE TITLE
Change parameters for GraphicMouseActionInterface

### ISSUE THREAD

**Issue by lifesbest23** [oripa/oripa#80]
I am working on my idea of adding a background image and I would like to add key modifiers for only dragging/scaling along the x or y axis. This is currently not possible as all onXXX functions only takes one `boolean differentAction` as a parameter and only uses the control key.
My idea would be to just use either the `MouseEvent` as an parameter type or at least its `getModifiersEx()` return value.
I am not sure though if this follows the design idea, at least it appears as one to me, to keep the Swing specific Classes mainly in oripa.view.* packages. But as AffineTransform is also utilized there and it is a, vaguely as controller categorizable, Interface, for me it seems reasonable.

I would like add this massive change, because I could see at least for LineSelectionAction the addition of select shortest path to last, or maybe a circle like draw to select function enabled by modifier keys.

Another Option would be to add another Interface, which could be Implemented by MouseActions and adds the modified functions on top. It would mean less code changes, but not really the best way.

In Addition I find some other irragularites in argument usage and function return types.

**Comment by lifesbest23** [comment]
Ok, just discovered that since java8 interfaces can have default function implementations with the modifier `default`. Did not know that, this would the easiest method.

**Comment by Ooouch1** [comment]
Seems you have found a solution but I leave some comments for your information.

> I would like to add key modifiers for only dragging/scaling along the x or y axis.

By "dragging/scaling" do you want to change the coordinate values of CP elements? Or just want to change how the CP seems?
If you want to change the coordinate values, it is reasonable to replace the parameter.
If you want to change the Affine matrix of the view only, I recommend to update the oripa.util.gui.AffineCamera and oripa.view.main.PainterScreen.

> AffineTransform is also utilized there

I think the AffineTransform parameter of GraphicMouseActionInterface should be removed because it is not used in any methods. We can get the logical mouse position through PaintContext and maybe that is enough to paint on logical coordinates.
